---
default: true
code-block-style:  # MD046
  style: fenced
emphasis-style: false  # MD049
header-style:  # MD003
  style: atx
hr-style:  # MD035
  style: "---"
line-length:
  line_length: 1800  # MD013
  headings: true
  heading_line_length: 100
  tables: false
no-duplicate-heading:  # MD024
  siblings_only: true
no-emphasis-as-heading: false  # MD036
no-inline-html: false  # MD033
no-trailing-punctuation:  # MD026
  punctuation: ".,;:!。，；：！"
no-trailing-spaces: false  # MD009
ol-prefix: false  # MD029
reference-links-images: false  # MD052
table-column-style: false  # MD060
no-multiple-blanks: false
no-bare-urls: false
MD025: false
MD055: false
MD056: false
MD059: false
proper-names:  # MD044
  code_blocks: false
  html_elements: false
  names:
    - DevOps
