---
yaml-files:
  - "*.yaml"
  - "*.yml"
ignore: []
rules:
  anchors: enable
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments:
    require-starting-space: true
    min-spaces-from-content: 2
    level: warning
  comments-indentation:
    level: warning
  document-end: disable
  document-start:
    present: true
    level: warning
  empty-lines: enable
  empty-values: disable
  float-values: disable
  hyphens: enable
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  octal-values: disable
  quoted-strings:
    required: false
    quote-type: double
  trailing-spaces: enable
  truthy:
    level: warning
